/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryAllCurrentUmOpenAlgoOrdersResponseInner
 */
export interface QueryAllCurrentUmOpenAlgoOrdersResponseInner {
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    algoId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    clientAlgoId?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    algoType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    orderType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    positionSide?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    quantity?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    algoStatus?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    actualOrderId?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    actualPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    triggerPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    icebergQuantity?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    tpTriggerPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    tpPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    slTriggerPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    slPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    tpOrderType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    selfTradePreventionMode?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    workingType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    priceMatch?: string;
    /**
     *
     * @type {boolean}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    closePosition?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    priceProtect?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    reduceOnly?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    createTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    updateTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    triggerTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllCurrentUmOpenAlgoOrdersResponseInner
     */
    goodTillDate?: number | bigint;
}
