/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin Pro WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin Pro WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PmProAccountUpdate
 */
export interface PmProAccountUpdate {
    /**
     *
     * @type {number | bigint}
     * @memberof PmProAccountUpdate
     */
    E?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof PmProAccountUpdate
     */
    u?: string;
    /**
     *
     * @type {string}
     * @memberof PmProAccountUpdate
     */
    eq?: string;
    /**
     *
     * @type {string}
     * @memberof PmProAccountUpdate
     */
    ae?: string;
    /**
     *
     * @type {string}
     * @memberof PmProAccountUpdate
     */
    im?: string;
    /**
     *
     * @type {string}
     * @memberof PmProAccountUpdate
     */
    mm?: string;
    /**
     *
     * @type {string}
     * @memberof PmProAccountUpdate
     */
    avb?: string;
    /**
     *
     * @type {string}
     * @memberof PmProAccountUpdate
     */
    vmw?: string;
}
