/* tslint:disable */

/**
 * Binance C2C REST API
 *
 * OpenAPI Specification for the Binance C2C REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetC2CTradeHistoryResponse
 */
export interface GetC2CTradeHistoryResponse {
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    orderNumber?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    advNo?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    tradeType?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    fiat?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    fiatSymbol?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    amount?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    totalPrice?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    unitPrice?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    orderStatus?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof GetC2CTradeHistoryResponse
     */
    createTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    commission?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    takerCommissionRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    takerCommission?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    takerAmount?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    counterPartNickName?: string;
    /**
     *
     * @type {string}
     * @memberof GetC2CTradeHistoryResponse
     */
    payMethodName?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof GetC2CTradeHistoryResponse
     */
    additionalKycVerify?: number | bigint;
}
